# Generated by Django 6.0 on 2025-12-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('merchantid', models.IntegerField()),
                ('fieldname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'etramenu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menuid', models.AutoField(primary_key=True, serialize=False)),
                ('merchantid', models.IntegerField()),
                ('productid', models.BigIntegerField()),
                ('availability', models.BooleanField()),
            ],
            options={
                'db_table': 'menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('merchantid', models.AutoField(primary_key=True, serialize=False)),
                ('nationalid', models.CharField(max_length=20)),
                ('merchantpaycode', models.CharField(max_length=20)),
                ('profilepicture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('businesstype', models.CharField(max_length=100)),
                ('accounttype', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('dateofcreation', models.DateField(null=True)),
            ],
            options={
                'db_table': 'merchant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=100)),
                ('productpicture', models.CharField(max_length=255)),
                ('amountinstock', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=50)),
                ('merchantid', models.IntegerField()),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('saleid', models.AutoField(primary_key=True, serialize=False)),
                ('merchantid', models.IntegerField()),
                ('productname', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'sales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('transfertype', models.CharField(max_length=50)),
                ('receiverid', models.IntegerField()),
                ('senderid', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'transaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('nationalid', models.CharField(max_length=20)),
                ('paycode', models.CharField(max_length=20)),
                ('profilepicture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('accounttype', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('dateofbirth', models.DateField(null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notificationid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('designated_to', models.CharField(choices=[('user', 'User'), ('merchant', 'Merchant'), ('all', 'All')], max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
