# Generated by Django 5.2 on 2025-12-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('customer_id', models.IntegerField()),
                ('customer_type', models.CharField(choices=[('user', 'User'), ('merchant', 'Merchant')], max_length=10)),
                ('customer_name', models.CharField(max_length=100)),
                ('merchant_id', models.IntegerField()),
                ('merchant_name', models.CharField(max_length=100)),
                ('table_name', models.CharField(blank=True, max_length=50, null=True)),
                ('items', models.JSONField()),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready for Pickup'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
    ]
